### ISSUE TITLE
Support better ZomboDB's Type Mapping

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-zombodb#2]
https://github.com/zombodb/zombodb/blob/master/TYPE-MAPPING.md

Idea: an additional field for ZomboDBIndex.

**Comment by gtsalles** [comment]
https://github.com/zombodb/zombodb/blob/master/TYPE-MAPPING.md#field-specific-mapping-functions

**Comment by fjsj** [comment]
Solved by #21
