### ISSUE TITLE
Add sed command on Makefile to match "# via django" lines

### ISSUE THREAD

**Issue by tcostam** [vintasoftware/django-zombodb#26]
### Description

On the dependency management part of the Makefile, remember to remove dependencies added to requirements.txt because of Django so you don't pin them as well.

```bash
sed '/django==/d' requirements.txt > requirements.tmp; mv requirements.tmp requirements.txt
sed '/# via django$$/d' requirements.txt > requirements.tmp; mv requirements.tmp requirements.txt
```

**Comment by fjsj** [comment]
Fixed by 525e2f23abe2b457f45b93c7ff3d88736d37cda5
